@echo off
echo Starting Alkhidmat Foundation Lahore website...
start cmd /k "npm run dev"
echo Waiting for server to start...
timeout /t 3 /nobreak >nul
echo Opening browser...
start http://localhost:5173
echo Done! You can keep the command window open to keep the server running.
